
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    if: github.repository == 'mcnaughtonadm/adme-py'

    steps:
      - uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
        env:
          RYE_VERSION: 0.33.0
          RYE_INSTALL_OPTION: '--yes'

      - name: Install dependencies
        run: |
          rye sync --all-features

      - name: Run ruff
        run: |
          rye lint

      - name: Ensure importable
        run: |
          rye run python -c 'import adme_py'
  test:
    name: test
    runs-on: ubuntu-latest
    if: github.repository == 'mcnaughtonadm/adme-py'

    steps:
      - uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
        env:
          RYE_VERSION: 0.33.0
          RYE_INSTALL_OPTION: '--yes'
      - name: Install dependencies
        run: |
          rye sync --all-features
          
      - name: Run tests
        run: rye test
